config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  Rails.application.routes.draw do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :cnabs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cnab.rb
class Cnab < ApplicationRecord
  has_one_attached :file
  has_many :purchases
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :cnab
  validates :transaction_type, :transaction_description, :transaction_action,
            :transaction_at, :amount, :cpf, :card_number, :transaction_hour,
            :store_owner, :store_name, presence: true

  def discount?
    transaction_action == 'discount'
  end

  def credit?
    transaction_action == 'sum'
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cnabs_controller.rb
class CnabsController < ApplicationController
  before_action :set_cnab, only: [:destroy, :show]

  def index
    @cnabs = Cnab.all
  end

  def new
    @cnab = Cnab.new
  end

  def show
    @purchases = @cnab.purchases
  end

  def create
    @cnab = Cnab.new(cnab_params)

    respond_to do |format|
      if @cnab.save
        CnabJob.perform_later(@cnab.id)
        format.html { redirect_to cnabs_path, notice: 'cnab was successfully created.' }
        format.json { render :show, status: :created, location: @cnab }
      else
        format.html { render :new }
        format.json { render json: @cnab.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_cnab
      @cnab = Cnab.find(params[:id])
    end

    def cnab_params
      params.fetch(:cnab).permit!
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cnabs_helper.rb
module CnabsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper

  def total_discount(purchases)
    purchases.select{ |purchase| purchase.discount? }.sum(&:amount).to_f

  end

  def total_credit(purchases)
    purchases.select{ |purchase| purchase.credit? }.sum(&:amount).to_f
  end
end

app/views/cnabs/_form.html.erb
<%= form_with(model: cnab, local: true) do |form| %>
  <% if cnab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cnab.errors.count, "error") %> prohibited this cnab from being saved:</h2>

      <ul>
        <% cnab.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :name %>
  <%= form.file_field :file %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cnabs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cnab</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cnabs.each do |cnab| %>
      <tr>
        <td><%= cnab.name %></td>
        <td><%= link_to 'Show', cnab %></td>
        <td><%= link_to 'Edit', edit_cnab_path(cnab) %></td>
        <td><%= link_to 'Destroy', cnab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New cnab', new_cnab_path %>

app/views/cnabs/new.html.erb
<h1>New Cnab</h1>

<%= render 'form', cnab: @cnab %>

<%= link_to 'Back', cnabs_path %>

app/views/cnabs/show.html.erb
<h1>COMPRAS</h1>


<table>
  <thead>
    <tr>
      <th>Nome da loja</th>
      <th>descrição</th>
      <th>valor</th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.store_name %></td>
        <td><%= purchase.transaction_description %></td>
        <td><%= number_to_currency(purchase.amount) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p> Total Ganhos:  <%= number_to_currency(total_credit(@purchases)) %></p>
<p> Total Debitos: <%= number_to_currency(total_discount(@purchases)) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pagnet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>